import{NextRequest,NextResponse}from'next/server';import{createClient}from'@supabase/supabase-js';
const sources=[
 {brand:'O Boticário',url:'https://www.boticario.com.br/todos-os-produtos/'},
 {brand:'Eudora',url:'https://www.eudora.com.br/site-todo/'},
 {brand:'Quem Disse, Berenice?',url:'https://www.quemdisseberenice.com.br/todos-produtos-site'},
 {brand:'O.U.i',url:'https://www.ouiparis.com/todos-os-produtos'}
];
type Item={name:string;image?:string;url?:string;sku?:string;brand:string};
const abs=(u:string,base:string)=>{try{return new URL(u,base).toString()}catch{return u}};
function collect(v:any,brand:string,base:string,out:Item[]){if(!v)return;if(Array.isArray(v)){v.forEach(x=>collect(x,brand,base,out));return}if(typeof v!=='object')return;const type=String(v['@type']??'').toLowerCase();if(type==='product'&&v.name){const image=Array.isArray(v.image)?v.image[0]:typeof v.image==='object'?v.image?.url:v.image;out.push({name:String(v.name).trim(),image:image?abs(String(image),base):undefined,url:v.url?abs(String(v.url),base):undefined,sku:v.sku?String(v.sku):undefined,brand})}Object.values(v).forEach(x=>collect(x,brand,base,out))}
async function scrape(src:{brand:string;url:string}){const html=await fetch(src.url,{headers:{'user-agent':'Mozilla/5.0 KarenMartinsCatalogBot/1.0'},cache:'no-store'}).then(r=>r.text());const out:Item[]=[];for(const m of html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{collect(JSON.parse(m[1]),src.brand,src.url,out)}catch{}}return [...new Map(out.map(x=>[(x.sku||x.url||x.name).toLowerCase(),x])).values()]}
export async function GET(req:NextRequest){if(req.headers.get('authorization')!==`Bearer ${process.env.CRON_SECRET}`)return NextResponse.json({error:'unauthorized'},{status:401});const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,key=process.env.SUPABASE_SERVICE_ROLE_KEY!;if(!url||!key)return NextResponse.json({error:'missing_configuration'},{status:500});const db=createClient(url,key);const{data:run}=await db.from('product_sync_runs').insert({sources:sources.map(x=>x.brand)}).select('id').single();let found=0,inserted=0,updated=0;try{for(const src of sources){const items=await scrape(src);found+=items.length;for(const p of items){const sourceKey=`${src.brand}:${p.sku||p.url||p.name}`;let existing:any=null;if(p.sku){const q=await db.from('products').select('id,image_url').eq('sku',p.sku).maybeSingle();existing=q.data}if(!existing){const q=await db.from('products').select('id,image_url').ilike('name',p.name).maybeSingle();existing=q.data}if(existing){await db.from('products').update({image_url:p.image||existing.image_url,source_url:p.url||src.url,source_key:sourceKey,source_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',existing.id);updated++}else{const{error}=await db.from('products').insert({sku:p.sku||null,name:p.name,brand:src.brand,image_url:p.image||null,source_url:p.url||src.url,source_key:sourceKey,source_checked_at:new Date().toISOString(),active:true,price:0});if(!error)inserted++}}}await db.from('product_sync_runs').update({finished_at:new Date().toISOString(),status:'SUCCESS',found_count:found,inserted_count:inserted,updated_count:updated}).eq('id',run?.id);return NextResponse.json({ok:true,found,inserted,updated})}catch(e:any){await db.from('product_sync_runs').update({finished_at:new Date().toISOString(),status:'ERROR',found_count:found,inserted_count:inserted,updated_count:updated,error_text:String(e?.message||e)}).eq('id',run?.id);return NextResponse.json({error:String(e?.message||e)},{status:500})}}
