'use server';
import{revalidatePath}from'next/cache';import{requireStaff}from'@/modules/auth/session';import{runCatalogSync,importOfficialProductByCode,type CatalogSyncMode}from'@/modules/catalog/sync-service';
const allowed=['Natura','Avon','O Boticário','Eudora','Quem Disse, Berenice?','O.U.i'];
const officialDomains:Record<string,string>={'Natura':'natura.com.br','Avon':'avon.com.br','O Boticário':'boticario.com.br','Eudora':'eudora.com.br','Quem Disse, Berenice?':'quemdisseberenice.com.br','O.U.i':'ouiparis.com'};
function isOfficialSource(brand:string|null,url:string){if(!brand||!url)return false;try{const host=new URL(url).hostname.toLowerCase().replace(/^www\./,'');const domain=officialDomains[brand];return !!domain&&(host===domain||host.endsWith('.'+domain))}catch{return false}}
export async function catalogQueueAction(formData:FormData){
  const{profile}=await requireStaff();
  if(!['SUPER_ADMIN','ADMIN'].includes(profile.role))return{ok:false,message:'Somente administradores podem executar a sincronização.'};
  const mode=String(formData.get('mode')||'process');const source=String(formData.get('source')||'');
  if(!['discover','repair','process'].includes(mode))return{ok:false,message:'Operação inválida.'};
  if(source&&!allowed.includes(source))return{ok:false,message:'Marca inválida.'};
  try{const body:any=await runCatalogSync(mode as CatalogSyncMode,source);revalidatePath('/catalogo');revalidatePath('/compras');if(mode==='discover'){const detail=body.bySource?Object.entries(body.bySource).map(([k,v])=>k+': '+v).join(' · '):'';const failures=body.sourceErrors&&Object.keys(body.sourceErrors).length?' Falhas: '+Object.entries(body.sourceErrors).map(([k,v])=>k+' ('+String(v)+')').join(' · '):'';return{ok:true,message:'Descoberta concluída: '+(body.discovered??0)+' URLs encontradas.'+(detail?' '+detail:'')+failures}}const prefix=mode==='repair'?'Reparo seguro: ':'Lote concluído: ';return{ok:true,message:prefix+(body.processed??0)+' processados, '+(body.inserted??0)+' novos, '+(body.updated??0)+' atualizados, '+(body.errors??0)+' erros.'}}catch(e:any){return{ok:false,message:String(e?.message||e)}}
}

export async function updateCatalogProductAction(formData:FormData){const{supabase,profile}=await requireStaff();if(!['SUPER_ADMIN','ADMIN'].includes(profile.role))return{ok:false,message:'Somente administradores podem editar produtos.'};const id=String(formData.get('id')||''),name=String(formData.get('name')||'').trim(),sku=String(formData.get('sku')||'').replace(/\D/g,''),source_code=String(formData.get('source_code')||'').trim()||null,brand=String(formData.get('brand')||'').trim()||null,category=String(formData.get('category')||'Não classificado').trim(),image_url=String(formData.get('image_url')||'').trim()||null,image_source_url=String(formData.get('image_source_url')||'').trim()||null,price=Number(String(formData.get('price')||'0').replace(',','.')),active=String(formData.get('active'))==='true';if(!id||!name||!sku)return{ok:false,message:'Nome e SKU numérico são obrigatórios.'};if(!Number.isFinite(price)||price<0)return{ok:false,message:'Preço inválido.'};if(image_url){try{const u=new URL(image_url);if(!['http:','https:'].includes(u.protocol))throw 0}catch{return{ok:false,message:'URL da imagem inválida.'}}}if(image_source_url&&!isOfficialSource(brand,image_source_url))return{ok:false,message:'A fonte da imagem precisa pertencer ao site oficial da marca.'};const verifiedImage=!!image_url&&isOfficialSource(brand,image_source_url||'');const now=new Date().toISOString();const{error}=await supabase.from('products').update({name,sku,source_code,brand,category,price,sale_price:price,active,image_url,image_status:verifiedImage?'VERIFIED':'PENDING',image_source_url:image_url?image_source_url:null,image_checked_at:image_url?now:null,updated_at:now}).eq('id',id);if(error)return{ok:false,message:error.code==='23505'?'Este SKU já está sendo usado por outro produto.':error.message};revalidatePath('/catalogo');revalidatePath('/pedidos');revalidatePath('/compras');return{ok:true,message:'Produto atualizado.'}}

export async function bulkCatalogAction(formData:FormData){const{supabase,profile}=await requireStaff();if(!['SUPER_ADMIN','ADMIN'].includes(profile.role))return{ok:false,message:'Somente administradores podem alterar produtos em massa.'};const ids=String(formData.get('ids')||'').split(',').map(v=>v.trim()).filter(Boolean);const action=String(formData.get('bulk_action')||'');if(!ids.length)return{ok:false,message:'Selecione ao menos um produto.'};if(ids.length>100)return{ok:false,message:'Limite de 100 produtos por operação.'};let patch:any={updated_at:new Date().toISOString()};if(action==='CATEGORY'){const value=String(formData.get('category')||'');if(!value)return{ok:false,message:'Selecione uma categoria.'};patch.category=value}else if(action==='ACTIVATE')patch.active=true;else if(action==='DEACTIVATE')patch.active=false;else if(action==='PRICE'){const raw=String(formData.get('price')||'').trim();if(!raw)return{ok:false,message:'Informe o preço explicitamente.'};const value=Number(raw.replace(',','.'));if(!Number.isFinite(value)||value<=0)return{ok:false,message:'Preço deve ser maior que zero.'};patch.price=value;patch.sale_price=value}else return{ok:false,message:'Ação em massa inválida.'};const{error}=await supabase.from('products').update(patch).in('id',ids);if(error)return{ok:false,message:error.message};revalidatePath('/catalogo');revalidatePath('/pedidos');revalidatePath('/compras');return{ok:true,message:ids.length+' produtos atualizados.'}}

export async function importCatalogProductByCodeAction(formData:FormData){const{profile}=await requireStaff();if(!['SUPER_ADMIN','ADMIN'].includes(profile.role))return{ok:false,message:'Somente administradores podem importar produtos.'};const code=String(formData.get('code')||'').trim();if(!code)return{ok:false,message:'Informe o código do produto.'};try{const r:any=await importOfficialProductByCode(code);if(!r.found)return{ok:false,message:r.message||'Produto não encontrado.'};revalidatePath('/catalogo');revalidatePath('/compras');return{ok:true,message:r.existing?'Produto já existe no catálogo: '+r.product.name:'Produto importado: '+r.product.name,product:r.product}}catch(e:any){return{ok:false,message:String(e?.message||e)}}}
