'use client';
import {useMemo,useState} from 'react';
import {Plus,Search,Trash2} from 'lucide-react';
import {criarPedidoCompraAction} from './actions';
type P={id:string;sku:string|null;name:string;brand:string|null;image_url?:string|null};
export function PurchaseBuilder({products,suppliers,needs=[]}:{products:P[];suppliers:string[];needs?:any[]}){
 const [items,setItems]=useState<any[]>([]),[plan,setPlan]=useState('30/60/90'),[dates,setDates]=useState<string[]>([]);
 const total=useMemo(()=>items.reduce((s,i)=>s+(Number(i.quantity)||0)*(Number(i.unit_cost)||0),0),[items]);
 const pendingNeeds=needs.filter(n=>Number(n.quantity_needed)>0);const add=()=>setItems(v=>[...v,{product_id:'',product_search:'',quantity:1,unit_cost:'',destination_type:'ESTOQUE'}]);const importNeeds=()=>setItems(pendingNeeds.map(n=>({product_id:n.product_id,product_search:`${n.sku??''} · ${n.name}`,quantity:Number(n.quantity_needed),unit_cost:'',destination_type:'VENDA_DIRETA'})));
 const matches=(q:string)=>{const t=q.trim().toLowerCase();if(!t)return[];return products.filter(p=>String(p.sku??'').toLowerCase().includes(t)||p.name.toLowerCase().includes(t)||String(p.brand??'').toLowerCase().includes(t)).slice(0,8)};
 const choose=(idx:number,p:P)=>setItems(v=>v.map((x,j)=>j===idx?{...x,product_id:p.id,product_search:`${p.sku??''} · ${p.name}`}:x));
 const installments=useMemo(()=>{const days=plan==='30/60/90'?[30,60,90]:plan==='20/40/60'?[20,40,60]:[];if(!days.length)return dates.filter(Boolean).map(d=>({due_date:d,amount:dates.filter(Boolean).length?total/dates.filter(Boolean).length:0}));return days.map(d=>{const x=new Date();x.setDate(x.getDate()+d);return{due_date:x.toISOString().slice(0,10),amount:total/days.length}})},[plan,dates,total]);
 return <form action={criarPedidoCompraAction} className="purchase-builder">
  {pendingNeeds.length>0&&<div className="purchase-demand-import"><div><b>Há {pendingNeeds.reduce((s,n)=>s+Number(n.quantity_needed),0)} itens vendidos por encomenda</b><span>Carregue a necessidade atual no pedido e informe somente os custos do fornecedor.</span></div><button type="button" className="primary" onClick={importNeeds}>Carregar encomendas no pedido</button></div>}<div className="purchase-head-grid"><label>Fornecedor<select name="supplier_name" required defaultValue=""><option value="" disabled>Selecione</option>{suppliers.map(s=><option key={s}>{s}</option>)}</select></label><label>Nº do pedido<input name="order_number" placeholder="Ex.: 531019386"/></label><label>Data do pedido<input name="ordered_at" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Pagamento<select name="payment_method" value={plan} onChange={e=>setPlan(e.target.value)}><option value="30/60/90">Boleto 30/60/90</option><option value="20/40/60">Boleto 20/40/60</option><option value="PERSONALIZADO">Personalizado</option><option value="PIX">PIX / à vista</option></select></label></div>
  <div className="purchase-items">{items.map((it,idx)=><div className="purchase-item" key={idx}><div className="product-autocomplete"><Search size={16}/><input autoComplete="off" value={it.product_search} onChange={e=>setItems(v=>v.map((x,j)=>j===idx?{...x,product_search:e.target.value,product_id:''}:x))} placeholder="Digite o código ou nome do produto"/>{it.product_search&&!it.product_id&&<div className="product-suggestions">{matches(it.product_search).length?matches(it.product_search).map(p=><button type="button" key={p.id} onClick={()=>choose(idx,p)}>{p.image_url?<img src={p.image_url} alt=""/>:<i className="suggestion-image-empty">Sem foto</i>}<div><b>{p.sku}</b><span>{p.name}</span><small>{p.brand}</small></div></button>):<span className="no-product-match">Nenhum produto encontrado na base</span>}</div>}{it.product_id&&<span className="product-found">Produto selecionado ✓</span>}</div><input type="number" min="1" value={it.quantity} onChange={e=>setItems(v=>v.map((x,j)=>j===idx?{...x,quantity:e.target.value}:x))} placeholder="Qtd"/><input type="number" min="0" step="0.01" value={it.unit_cost} onChange={e=>setItems(v=>v.map((x,j)=>j===idx?{...x,unit_cost:e.target.value}:x))} placeholder="Custo nesta compra"/><select value={it.destination_type} onChange={e=>setItems(v=>v.map((x,j)=>j===idx?{...x,destination_type:e.target.value}:x))}><option value="ESTOQUE">Pronta entrega</option><option value="VENDA_DIRETA">Atender encomendas</option></select><button type="button" className="secondary" onClick={()=>setItems(v=>v.filter((_,j)=>j!==idx))}><Trash2 size={16}/></button></div>)}</div>
  <button type="button" className="secondary" onClick={add}><Plus size={16}/>Adicionar produto</button>
  {plan==='PERSONALIZADO'&&<div className="custom-dates"><b>Vencimentos personalizados</b>{dates.map((d,i)=><input key={i} type="date" value={d} onChange={e=>setDates(v=>v.map((x,j)=>j===i?e.target.value:x))}/>)}<button type="button" className="secondary" onClick={()=>setDates(v=>[...v,''])}>+ Parcela</button></div>}
  <div className="purchase-total"><span>Total da compra</span><strong>{total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><small>{installments.length?installments.map(x=>new Date(x.due_date+'T12:00').toLocaleDateString('pt-BR')).join(' · '):'À vista / sem parcelas'}</small></div>
  <input type="hidden" name="items_json" value={JSON.stringify(items)}/><input type="hidden" name="installments_json" value={JSON.stringify(plan==='PIX'?[]:installments)}/><textarea name="notes" placeholder="Observações do pedido"/><button className="primary" disabled={!items.length||items.some(i=>!i.product_id)}>Registrar pedido e contas a pagar</button>
 </form>
}