import{Boxes,Eye,EyeOff,PackageCheck,TrendingUp}from'lucide-react';
import{requireStaff}from'@/modules/auth/session';
import{StaffNav}from'@/components/staff-nav';
import{salvarProntaEntregaAction,entradaManualEstoqueAction}from'./actions';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
export default async function Estoque(){
 const{supabase,profile}=await requireStaff();
 const[{data},{data:catalog}]=await Promise.all([supabase.from('inventory_lots').select('id,quantity_available,unit_cost,received_at,products(id,sku,name,brand,image_url),ready_stock(sale_price,visible)').gt('quantity_available',0).order('received_at',{ascending:false}),supabase.from('products').select('id,sku,name,brand').eq('active',true).order('name')]);
 const lots=(data??[])as any[],qty=lots.reduce((s,x)=>s+Number(x.quantity_available),0),cost=lots.reduce((s,x)=>s+Number(x.quantity_available)*Number(x.unit_cost),0);
 const grouped=new Map<string,any>();
 for(const x of lots){const p=x.products;if(!p)continue;const g=grouped.get(p.id)??{product:p,qty:0,cost:0,lots:0,ready:x.ready_stock};g.qty+=Number(x.quantity_available);g.cost+=Number(x.quantity_available)*Number(x.unit_cost);g.lots++;if(x.ready_stock)g.ready=x.ready_stock;grouped.set(p.id,g)}
 const products=[...grouped.values()].sort((a,b)=>String(a.product.name).localeCompare(String(b.product.name),'pt-BR'));
 const projected=products.reduce((s,x)=>s+(x.ready?.visible&&x.ready?.sale_price?x.qty*Number(x.ready.sale_price):0),0);
 return <><StaffNav profile={profile} active="estoque"/><main className="clients-page with-app-nav"><div className="clients-wrap">
 <header className="clients-header"><div><p className="eyebrow">PRONTA ENTREGA</p><h1>Estoque</h1><p className="muted">Custo preservado por lote e preço de venda independente. Produtos podem ser publicados ou ocultados da pronta entrega.</p></div></header>
 <div className="stats"><article className="stat"><div className="stat-icon"><Boxes/></div><span>Unidades disponíveis</span><strong>{qty}</strong><small>{products.length} produtos</small></article><article className="stat"><div className="stat-icon"><PackageCheck/></div><span>Custo do estoque</span><strong>{money.format(cost)}</strong><small>valor pelo custo real de cada lote</small></article><article className="stat"><div className="stat-icon"><TrendingUp/></div><span>Venda projetada</span><strong>{money.format(projected)}</strong><small>somente itens publicados com preço</small></article></div>
 <section className="client-form-card"><div className="list-heading"><div><p className="eyebrow">ESTOQUE INICIAL / AJUSTE</p><h2>Entrada manual</h2><p className="muted">Para mercadorias que já existem fisicamente, sem criar compra fictícia.</p></div></div><form action={entradaManualEstoqueAction} className="manual-stock-form"><select name="product_id" required defaultValue=""><option value="" disabled>Produto</option>{(catalog??[]).map((p:any)=><option value={p.id} key={p.id}>{p.sku} · {p.name}</option>)}</select><input name="quantity" type="number" min="1" required placeholder="Quantidade"/><input name="unit_cost" type="number" min="0" step="0.01" required placeholder="Custo unitário"/><input name="notes" placeholder="Observação (opcional)"/><button className="primary">Dar entrada</button></form></section><section className="client-list-card"><div className="list-heading"><div><p className="eyebrow">CATÁLOGO DE PRONTA ENTREGA</p><h2>Produtos disponíveis</h2></div></div><div className="product-list">{products.map(x=>{const avg=x.qty?x.cost/x.qty:0,price=Number(x.ready?.sale_price||0),margin=price?price-avg:0;return <article className="product-row" key={x.product.id}>{x.product.image_url?<img className="product-thumb" src={x.product.image_url} alt=""/>:<span className="product-thumb product-thumb-empty"><PackageCheck size={20}/></span>}<div><span>{x.product.brand} · código {x.product.sku}</span><strong>{x.product.name}</strong><small>{x.lots} lote{x.lots===1?'':'s'} · custo médio {money.format(avg)}</small></div><div><small>Disponível</small><b>{x.qty}</b></div><div><small>Margem unitária</small><b>{price?money.format(margin):'—'}</b></div><form action={salvarProntaEntregaAction} className="stock-price-form"><input type="hidden" name="product_id" value={x.product.id}/><label><small>Preço de venda</small><input name="sale_price" type="number" min="0" step="0.01" defaultValue={price||''} placeholder="0,00"/></label><label className="stock-visible"><input name="visible" type="checkbox" defaultChecked={Boolean(x.ready?.visible)}/>{x.ready?.visible?<Eye size={16}/>:<EyeOff size={16}/>} Pronta entrega</label><button className="secondary">Salvar</button></form></article>})}</div>{!products.length&&<div className="empty-clients"><Boxes size={32}/><strong>Estoque vazio</strong><span>Receba um pedido em Compras para gerar a entrada.</span></div>}</section>
 </div></main></>;
}