'use client';
import{useMemo,useState}from'react';import{Plus,Search,ShoppingBag,Trash2}from'lucide-react';import{criarPedidoAction}from'./actions';
type P={id:string;sku:string|null;name:string;brand:string|null;image_url?:string|null};type C={id:string;name:string};type I={product:P|null,q:string,quantity:number,unit_price:string,fulfillment_type:'ESTOQUE'|'ENCOMENDA'};
export function NewSaleOrder({clients,consortia,products}:{clients:C[];consortia:C[];products:P[]}){
 const[items,setItems]=useState<I[]>([{product:null,q:'',quantity:1,unit_price:'',fulfillment_type:'ENCOMENDA'}]);
 const match=(q:string)=>{const t=q.trim().toLowerCase();return t?products.filter(p=>String(p.sku??'').includes(t)||p.name.toLowerCase().includes(t)||String(p.brand??'').toLowerCase().includes(t)).slice(0,8):[]};
 const change=(i:number,v:Partial<I>)=>setItems(x=>x.map((a,j)=>j===i?{...a,...v}:a));
 const total=useMemo(()=>items.reduce((s,i)=>s+i.quantity*(Number(i.unit_price)||0),0),[items]);
 return <form action={criarPedidoAction} className="order-form sale-order-autocomplete"><select name="client_id" required defaultValue=""><option value="" disabled>Cliente</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select name="consortium_id" defaultValue=""><option value="">Compra avulsa / sem consórcio</option>{consortia.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select>
 <div className="purchase-items">{items.map((it,idx)=><div className="purchase-item" key={idx}><div className="product-autocomplete sale-product-search"><Search size={16}/><input autoComplete="off" value={it.q} onChange={e=>change(idx,{q:e.target.value,product:null})} placeholder="Código numérico ou nome"/>{it.q&&!it.product&&<div className="product-suggestions">{match(it.q).length?match(it.q).map(p=><button type="button" key={p.id} onClick={()=>change(idx,{product:p,q:`${p.sku} · ${p.name}`})}>{p.image_url?<img src={p.image_url} alt=""/>:<i className="suggestion-image-empty">Sem foto</i>}<div><b>{p.sku}</b><span>{p.name}</span><small>{p.brand}</small></div></button>):<span className="no-product-match">Produto não cadastrado. Use o cadastro rápido em Compras e volte ao pedido.</span>}</div>}</div><input type="number" min="1" value={it.quantity} onChange={e=>change(idx,{quantity:Math.max(1,Number(e.target.value))})}/><input type="number" min="0" step="0.01" value={it.unit_price} onChange={e=>change(idx,{unit_price:e.target.value})} placeholder="Valor unitário"/><select value={it.fulfillment_type} onChange={e=>change(idx,{fulfillment_type:e.target.value as any})}><option value="ESTOQUE">Pronta entrega</option><option value="ENCOMENDA">Vou pedir / encomenda</option></select><button type="button" className="secondary" onClick={()=>setItems(x=>x.filter((_,j)=>j!==idx))} disabled={items.length===1}><Trash2 size={16}/></button></div>)}</div>
 <button type="button" className="secondary" onClick={()=>setItems(x=>[...x,{product:null,q:'',quantity:1,unit_price:'',fulfillment_type:'ENCOMENDA'}])}><Plus size={16}/>Adicionar produto</button><div className="purchase-total"><span>Total da venda</span><strong>{total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><small>Voucher será tratado como forma de pagamento, não como desconto/prejuízo.</small></div>
 <input type="hidden" name="items_json" value={JSON.stringify(items.filter(i=>i.product).map(i=>({product_id:i.product!.id,quantity:i.quantity,unit_price:Number(i.unit_price)||0,fulfillment_type:i.fulfillment_type})))}/><label>Código do voucher (opcional)<input name="voucher_code" placeholder="Código único do voucher"/></label><button className="primary" disabled={!items.length||items.some(i=>!i.product)}><ShoppingBag size={16}/>Confirmar venda</button></form>
}