'use client';import{FormEvent,useState}from'react';import{BookOpen,Eye,EyeOff,Pencil,Plus,Save,Trash2,X}from'lucide-react';
type Row={id:string;brand:string;title:string;cycle:string|null;view_url:string|null;download_url:string|null;active:boolean;sort_order:number};
const brands=['Natura','O Boticário','Eudora','O.U.i','Avon','Outra'];
export function MagazineManager({initialRows}:{initialRows:Row[]}){const[rows,setRows]=useState(initialRows),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Row|null>(null);
async function send(method:string,body:any){setBusy(true);const r=await fetch('/api/admin/revistas',{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});setBusy(false);if(!r.ok){alert((await r.json()).error??'Erro ao salvar revista.');return false}location.reload();return true}
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),body=Object.fromEntries(fd.entries());await send('POST',{...body,sort_order:Number(body.sort_order||0)})}
async function update(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const fd=new FormData(e.currentTarget),body=Object.fromEntries(fd.entries());await send('PATCH',{...editing,...body,active:fd.get('active')==='on',sort_order:Number(fd.get('sort_order')||0)})}
async function toggle(r:Row){await send('PATCH',{...r,active:!r.active})}
async function remove(id:string){if(!confirm('Remover esta revista?'))return;const r=await fetch('/api/admin/revistas?id='+id,{method:'DELETE'});if(r.ok)setRows(x=>x.filter(a=>a.id!==id));else alert((await r.json()).error??'Erro ao remover.')}
const fields=(r?:Row|null)=><><label><span>Marca</span><select name="brand" required defaultValue={r?.brand??''}><option value="" disabled>Selecione</option>{brands.map(b=><option key={b}>{b}</option>)}</select></label><label><span>Título</span><input name="title" required defaultValue={r?.title??''} placeholder="Ex.: Revista Natura Ciclo 15"/></label><label><span>Ciclo</span><input name="cycle" defaultValue={r?.cycle??''} placeholder="Ex.: Ciclo 15/2026"/></label><label><span>Ordem no mural</span><input name="sort_order" type="number" min="0" defaultValue={r?.sort_order??0}/></label><label className="full"><span>Link para visualizar</span><input name="view_url" type="url" required defaultValue={r?.view_url??''} placeholder="https://..."/></label><label className="full"><span>Link para baixar (opcional)</span><input name="download_url" type="url" defaultValue={r?.download_url??''} placeholder="https://..."/></label></>;
return <><section className="client-form-card"><div className="form-heading"><div><p className="eyebrow">NOVA REVISTA</p><h2>Publicar revista</h2><p className="muted">Cadastre o ciclo uma vez e ele aparecerá no mural do portal do cliente.</p></div><BookOpen/></div><form className="magazine-form" onSubmit={save}>{fields()}<button className="primary" disabled={busy}><Plus size={17}/>{busy?'Publicando...':'Publicar revista'}</button></form></section>
<section className="client-list-card"><div className="list-heading"><div><p className="eyebrow">PUBLICADAS</p><h2>Revistas disponíveis</h2><p className="muted">Edite, oculte ciclos antigos ou defina a ordem do mural sem apagar o histórico.</p></div><strong>{rows.length}</strong></div>{rows.length===0?<div className="empty-clients"><BookOpen size={30}/><strong>Nenhuma revista publicada</strong><span>Use o formulário acima para publicar o primeiro ciclo.</span></div>:<div className="magazine-admin-list">{rows.map(r=><article key={r.id} className={!r.active?'magazine-inactive':''}><div><strong>{r.brand} · {r.title}</strong><span>{r.cycle||'Sem ciclo'} · Ordem {r.sort_order} · {r.active?'Visível no portal':'Oculta'}</span></div>{r.view_url&&<a href={r.view_url} target="_blank" rel="noreferrer">Abrir</a>}<button className="icon" onClick={()=>toggle(r)} title={r.active?'Ocultar':'Publicar'}>{r.active?<Eye size={16}/>:<EyeOff size={16}/>}</button><button className="icon" onClick={()=>setEditing(r)} title="Editar"><Pencil size={16}/></button><button className="icon" onClick={()=>remove(r.id)} title="Remover"><Trash2 size={16}/></button></article>)}</div>}</section>
{editing&&<div className="client-pix-overlay"><div className="client-pix-modal magazine-edit-modal"><button className="client-pix-close" onClick={()=>setEditing(null)}><X size={18}/></button><div><p className="eyebrow">EDITAR REVISTA</p><h2>{editing.brand} · {editing.cycle||editing.title}</h2></div><form className="magazine-form" onSubmit={update}>{fields(editing)}<label className="magazine-active-toggle"><input type="checkbox" name="active" defaultChecked={editing.active}/><span>Visível no portal do cliente</span></label><button className="primary" disabled={busy}><Save size={17}/>{busy?'Salvando...':'Salvar alterações'}</button></form></div></div>}</>}