'use client';
import {useState,useTransition} from'react';
import{revisarSolicitacaoAcessoAction,regenerarCodigoAcessoAction}from'./access-actions';
type Item={id:string;phone:string;status:string;request_type:string;requested_at:string;activation_expires_at:string|null;activation_attempts:number;clients:{name:string}|null};
export function SolicitacoesAcesso({items}:{items:Item[]}){const[code,setCode]=useState('');const[pending,start]=useTransition();if(!items.length&&!code)return null;
function review(id:string,approve:boolean){const f=new FormData();f.set('id',id);f.set('decision',approve?'approve':'reject');start(async()=>{const r=await revisarSolicitacaoAcessoAction(f);if(r)setCode(r);});}
function regen(id:string){const f=new FormData();f.set('id',id);start(async()=>{const r=await regenerarCodigoAcessoAction(f);if(r)setCode(r);});}
return <section className="client-list-card" style={{marginBottom:20}}><div className="list-heading"><div><p className="eyebrow">ACESSO AO APP</p><h2>Ativação de clientes</h2></div><strong>{items.length} solicitação{items.length===1?'':'ões'}</strong></div>
{code&&<div style={{padding:16,borderRadius:14,background:'#fff4f8',margin:'0 16px 16px'}}><strong>Novo código: {code}</strong><p className="muted" style={{marginBottom:0}}>Copie e envie ao cliente. Válido por 24 horas e exibido somente agora.</p><button type="button" onClick={()=>setCode('')} style={{marginTop:8}}>Fechar</button></div>}
<div style={{display:'grid',gap:10,padding:16}}>{items.map(r=>{const approved=r.status==='APROVADA';const expired=approved&&(!r.activation_expires_at||new Date(r.activation_expires_at)<=new Date());const blocked=approved&&r.activation_attempts>=5;return <div key={r.id} style={{display:'flex',gap:12,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap',padding:'12px 0',borderBottom:'1px solid #eee'}}><div><strong>{r.clients?.name??'Cliente'}</strong><div className="muted">{r.phone} · {r.request_type==='PASSWORD_RESET'?'Recuperação de senha':'Primeiro acesso'} · {approved?(blocked?'Código bloqueado':expired?'Código expirado':'Aguardando conclusão'):'Aguardando aprovação'}</div></div><div style={{display:'flex',gap:8}}>{approved?<button type="button" className="primary" disabled={pending} onClick={()=>regen(r.id)}>Gerar novo código</button>:<><button type="button" disabled={pending} onClick={()=>review(r.id,false)}>Rejeitar</button><button type="button" className="primary" disabled={pending} onClick={()=>review(r.id,true)}>Aprovar</button></>}</div></div>})}</div></section>}