import{ArrowDownCircle,ArrowUpCircle,CalendarClock,CircleDollarSign,Landmark,TriangleAlert,WalletCards}from'lucide-react';
import{requireStaff}from'@/modules/auth/session';
import{StaffNav}from'@/components/staff-nav';

const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:string)=>new Date(v+'T12:00:00').toLocaleDateString('pt-BR');
const n=(v:any)=>Number(v??0);

export default async function Financeiro(){
 const{supabase,profile}=await requireStaff();
 const today=new Date(),todayKey=today.toISOString().slice(0,10),monthStart=new Date(today.getFullYear(),today.getMonth(),1).toISOString().slice(0,10),nextMonth=new Date(today.getFullYear(),today.getMonth()+1,1).toISOString().slice(0,10);
 const[{data:pay},{data:rec},{data:paidRec},{data:orders},{data:vouchers},{data:sales},{data:saleDebts},{data:saleDebtPaid},{data:salePayments},{data:cashExpenses}]=await Promise.all([
  supabase.from('accounts_payable').select('id,supplier_name,description,due_date,amount,status,paid_at,paid_amount,payment_method').order('due_date'),
  supabase.from('installments').select('id,due_date,amount,status').in('status',['A_VENCER','VENCIDA']).order('due_date'),
  supabase.from('installments').select('id,amount,paid_at,status').eq('status','PAGA').gte('paid_at',monthStart).lt('paid_at',nextMonth),
  supabase.from('purchase_orders').select('id,total_amount,status,ordered_at,received_at,payment_method'),
  supabase.from('vouchers').select('id,original_credit,available_balance,reserved_balance,status'),supabase.from('customer_orders').select('id,subtotal,voucher_amount,pix_received,sale_confirmed_at,delivered_at,status,customer_order_items(inventory_cost,fulfillment_status)').not('delivered_at','is',null).gte('delivered_at',monthStart).lt('delivered_at',nextMonth),supabase.from('customer_order_debt_installments').select('id,amount,due_date,status,clients(name)').in('status',['PENDENTE','VENCIDA']).order('due_date'),supabase.from('customer_order_debt_installments').select('id,amount,paid_at,status').eq('status','PAGA').gte('paid_at',monthStart).lt('paid_at',nextMonth),supabase.from('customer_order_payments').select('id,method,amount,created_at').gte('created_at',monthStart).lt('created_at',nextMonth),supabase.from('cash_movements').select('id,amount,created_at,type,description').eq('type','DESPESA').gte('created_at',monthStart).lt('created_at',nextMonth)
 ]);
 const payable=(pay??[])as any[],receivable=(rec??[])as any[],paid=(paidRec??[])as any[],purchases=(orders??[])as any[],vs=(vouchers??[])as any[];
 const saleReceivable=(saleDebts??[])as any[],salePaid=(saleDebtPaid??[])as any[];const openPay=payable.filter(x=>x.status!=='PAGO'&&x.status!=='CANCELADO'),p=openPay.reduce((s,x)=>s+n(x.amount),0),r=receivable.reduce((s,x)=>s+n(x.amount),0)+saleReceivable.reduce((s,x)=>s+n(x.amount),0);
 const overdueRec=[...receivable.filter(x=>x.due_date<todayKey),...saleReceivable.filter(x=>x.status==='VENCIDA'||x.due_date<todayKey)],overduePay=openPay.filter(x=>x.due_date<todayKey);
 const paymentRows=(salePayments??[])as any[],receivedMonth=paid.reduce((s,x)=>s+n(x.amount),0)+paymentRows.reduce((s,x)=>s+n(x.amount),0),paidMonth=payable.filter(x=>x.status==='PAGO'&&x.paid_at&&String(x.paid_at).slice(0,10)>=monthStart&&String(x.paid_at).slice(0,10)<nextMonth).reduce((s,x)=>s+n(x.paid_amount||x.amount),0);
 const cashExpenseMonth=(cashExpenses??[]).reduce((s:any,x:any)=>s+n(x.amount),0),boughtMonth=purchases.filter(x=>x.ordered_at>=monthStart&&x.ordered_at<nextMonth).reduce((s,x)=>s+n(x.total_amount),0),netCash=receivedMonth-paidMonth-cashExpenseMonth;
 const monthSales=(sales??[]).filter((x:any)=>x.status==='ENTREGUE'),cashSales=paymentRows.reduce((s,x)=>s+n(x.amount),0),salesRevenue=monthSales.reduce((s:any,x:any)=>s+n(x.subtotal),0),voucherSales=monthSales.reduce((s:any,x:any)=>s+n(x.voucher_amount),0),cogs=monthSales.reduce((s:any,x:any)=>s+(x.customer_order_items??[]).filter((i:any)=>i.fulfillment_status==='ENTREGUE').reduce((a:any,i:any)=>a+n(i.inventory_cost),0),0),grossMargin=salesRevenue-cogs;const voucherFace=vs.reduce((s,x)=>s+n(x.original_credit),0),voucherAvailable=vs.reduce((s,x)=>s+n(x.available_balance),0),voucherReserved=vs.reduce((s,x)=>s+n(x.reserved_balance),0);
 const next=[...receivable.map(x=>({...x,type:'RECEBER'})),...saleReceivable.map(x=>({...x,type:'VENDA'})),...openPay.map(x=>({...x,type:'PAGAR'}))].sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(0,12);
 return <><StaffNav profile={profile} active="financeiro"/><main className="clients-page with-app-nav"><div className="clients-wrap">
  <header className="clients-header"><div><p className="eyebrow">CENTRAL FINANCEIRA</p><h1>Financeiro</h1><p className="muted">Caixa, compromissos, recebimentos e vouchers separados para não confundir crédito do cliente com dinheiro da operação.</p></div></header>
  <div className="stats">
   <article className="stat"><div className="stat-icon"><ArrowUpCircle/></div><span>A receber</span><strong>{money.format(r)}</strong><small>{receivable.length} consórcio · {saleReceivable.length} vendas</small></article>
   <article className="stat"><div className="stat-icon"><ArrowDownCircle/></div><span>A pagar</span><strong>{money.format(p)}</strong><small>{openPay.length} compromissos</small></article>
   <article className="stat"><div className="stat-icon"><WalletCards/></div><span>Saldo projetado</span><strong>{money.format(r-p)}</strong><small>consórcios e vendas menos compromissos</small></article>
   <article className="stat"><div className="stat-icon"><CircleDollarSign/></div><span>Recebido no mês</span><strong>{money.format(receivedMonth)}</strong><small>consórcios + vendas efetivamente recebidos</small></article>
  </div>
  <div className="stats">
   <article className="stat"><div className="stat-icon"><Landmark/></div><span>Compras no mês</span><strong>{money.format(boughtMonth)}</strong><small>pedidos emitidos no período</small></article>
   <article className="stat"><div className="stat-icon"><ArrowDownCircle/></div><span>Pago a fornecedores</span><strong>{money.format(paidMonth)}</strong><small>baixas efetivamente registradas</small></article><article className="stat"><div className="stat-icon"><WalletCards/></div><span>Fluxo líquido do mês</span><strong>{money.format(netCash)}</strong><small>recebimentos − fornecedores − despesas de caixa</small></article>
   <article className="stat"><div className="stat-icon"><ArrowDownCircle/></div><span>Despesas de caixa</span><strong>{money.format(cashExpenseMonth)}</strong><small>saídas operacionais lançadas no caixa</small></article><article className="stat"><div className="stat-icon"><TriangleAlert/></div><span>Em atraso</span><strong>{money.format(overdueRec.reduce((s,x)=>s+n(x.amount),0))}</strong><small>{overdueRec.length} recebíveis · {overduePay.length} contas a pagar</small></article>
   <article className="stat"><div className="stat-icon"><CalendarClock/></div><span>Vouchers disponíveis</span><strong>{money.format(voucherAvailable)}</strong><small>{money.format(voucherReserved)} reservado · face {money.format(voucherFace)}</small></article>
  </div>
  <section className="client-list-card"><div className="list-heading"><div><p className="eyebrow">RESULTADO DO MÊS</p><h2>DRE comercial por competência</h2><p className="muted">Receita e CMV são reconhecidos na entrega. Voucher é forma de pagamento e não reduz a receita.</p></div></div><div className="stats"><article className="stat"><span>Receita de vendas</span><strong>{money.format(salesRevenue)}</strong><small>{monthSales.length} vendas entregues</small></article><article className="stat"><span>CMV apurado</span><strong>{money.format(cogs)}</strong><small>custo FIFO dos itens entregues</small></article><article className="stat"><span>Margem bruta</span><strong>{money.format(grossMargin)}</strong><small>{salesRevenue?((grossMargin/salesRevenue)*100).toFixed(1):'0,0'}% sobre vendas</small></article><article className="stat"><span>Caixa recebido em vendas</span><strong>{money.format(cashSales)}</strong><small>entrada + parcelas recebidas no mês</small></article><article className="stat"><span>Vouchers usados</span><strong>{money.format(voucherSales)}</strong><small>forma de pagamento · não reduz receita</small></article><article className="stat"><span>PIX recebido</span><strong>{money.format(paymentRows.filter(x=>x.method==='PIX').reduce((s,x)=>s+n(x.amount),0))}</strong><small>vendas no período</small></article><article className="stat"><span>Dinheiro recebido</span><strong>{money.format(paymentRows.filter(x=>x.method==='DINHEIRO').reduce((s,x)=>s+n(x.amount),0))}</strong><small>vendas no período</small></article><article className="stat"><span>Cartão recebido</span><strong>{money.format(paymentRows.filter(x=>x.method==='CARTAO').reduce((s,x)=>s+n(x.amount),0))}</strong><small>vendas no período</small></article></div></section><section className="client-list-card"><div className="list-heading"><div><p className="eyebrow">AGENDA FINANCEIRA</p><h2>Próximos vencimentos</h2></div></div><div className="product-list">{next.length?next.map((x:any)=><article className="product-row" key={x.type+x.id}><div><span>{x.type==='PAGAR'?'Pagamento previsto':'Recebimento previsto'} · {date(x.due_date)}</span><strong>{x.type==='RECEBER'?'Parcela de consórcio':x.type==='VENDA'?`Parcela de venda · ${x.clients?.name??'Cliente'}`:x.description}</strong>{x.type==='PAGAR'&&<small>{x.supplier_name}</small>}</div><div><small>Valor</small><b>{money.format(n(x.amount))}</b></div><span className={x.due_date<todayKey?'danger':'secondary'}>{x.due_date<todayKey?'ATRASADO':x.type}</span></article>):<p className="muted">Nenhum vencimento pendente.</p>}</div></section>
  <section className="client-list-card"><div className="list-heading"><div><p className="eyebrow">CONTAS A PAGAR</p><h2>Fornecedores</h2></div></div><div className="product-list">{openPay.length?openPay.map((x:any)=><article className="product-row" key={x.id}><div><span>{x.supplier_name} · vence {date(x.due_date)}</span><strong>{x.description}</strong></div><div><small>Valor</small><b>{money.format(n(x.amount))}</b></div><span className={x.due_date<todayKey?'danger':'secondary'}>{x.due_date<todayKey?'ATRASADO':x.status}</span></article>):<p className="muted">Nenhuma conta de fornecedor em aberto.</p>}</div></section>
  
 </div></main></>;
}